name: Run Unit Tests

on:
  push:
  pull_request: 

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
      - name: Run Tests
        run: |
          python -m unittest discover backend/ML/testing.py  
